### ISSUE TITLE
Link Playback and Recording devices together

### ISSUE THREAD

**Issue by kenijo** [Belphemur/SoundSwitch#328] opened 2019-03-15 19:31 UTC
Hello,

I was thinking it would be great to be able to link the Playback and Recording devices together so that when you change one, it changes the other one as well.

Let me explain. My laptop has a speaker and a microphone. I also have a headset with a microphone plugged to my laptop. I would love to be able to "just" switch once between laptop and headset. And not twice, from Laptop Speaker and Laptop Microphone to Headset Speaker and Headset Microphone.

What do you think? Does it make sense?

**Comment by Belphemur** [comment] 2019-03-15 19:43
Hello,

This idea is already present in the list of issues.

Duplicate of #207

**Closed by Belphemur** 2019-03-15 19:43 UTC
Labels: Invalid-Duplicate
