### ISSUE TITLE
SoundSwitch 'forgets' nVidia HDMI audio output

### ISSUE THREAD

**Issue by neogohan324** [Belphemur/SoundSwitch#1114] opened 2023-02-09 20:28 UTC
### What happened?

I use SoundSwitch predominantly to switch output to my TV/AVR when Big Picture is activated, however I've found that SoundSwitch regularly forgets this output exists.

See this as an example:
![image](https://user-images.githubusercontent.com/30501522/217927045-63600641-f69d-4a37-947d-248b3b3738f7.png)

The "DENON-AVR" output is the HDMI output on my nVidia card (3060 Ti, driver version 528.34), however it's conspicuously absent from SoundSwitch's list. That wasn't always the case, though -- I did set it before as the output in a profile, but now it displays a "[Render]..." output for that profile, and if I try to view the profile, it doesn't display in the selection.

![image](https://user-images.githubusercontent.com/30501522/217927486-df23b5f5-abf1-4fc4-b268-7191132ca0fc.png)
![image](https://user-images.githubusercontent.com/30501522/217927524-4b0dfab5-5977-4f47-a010-fd2a781dbba8.png)

Additionally, when I do start "Big Picture" mode in Steam, the profile triggers, but it displays an error about not being able to find the device.

Here are the logs I have from the past 2 days:
[soundswitch20230208.log](https://github.com/Belphemur/SoundSwitch/files/10701198/soundswitch20230208.log)
[soundswitch20230209.log](https://github.com/Belphemur/SoundSwitch/files/10701199/soundswitch20230209.log)

Lastly, if I stop and restart SoundSwitch, the "DENON-AVR" output now appears:

![image](https://user-images.githubusercontent.com/30501522/217928346-ebb9ba74-5fd9-4147-8159-eda781019348.png)

This seems to be an issue of the output being 'lost' somehow and not rediscovered.

### Step to reproduce

I'm not entirely sure how to reproduce at this time, and I'm not sure what causes the "DENON-AVR" output to disappear.

I'm sorry I can't provide more information to help reproduce. Let me know if there is anything useful I may have forgotten.

### Version

v6.5.3

### What version of Windows are you seeing the problem on?

Windows 10

**Comment by Belphemur** [comment] 2023-02-09 20:30
Duplicate of #1113 

Please see more there, you can test the nightly version that has the fix:
https://soundswitch.aaflalo.me/nightly

You'll have to manually stop SoundSwitch and override its file with the content of the zip.

**Comment by Belphemur** [comment] 2023-02-09 20:31
Duplicate of #1113

**Closed by Belphemur** 2023-02-09 20:30 UTC
Labels: Bug, Invalid-Duplicate

**Comment by neogohan324** [comment] 2023-02-09 20:38
That's what I get for not checking the "closed" issues. 

Thanks for the link to the nightly! I'll try it and report back in #1113

**Comment by Belphemur** [comment] 2023-02-09 21:03
To be honest, the closed issues aren't always clear ^^

Moreover, your bug report was actually way more detail than the original one.
Thanks for taking the time !

I'm happy the nightly fixes the issue, I'll release it later today.
