### ISSUE TITLE
Icon in notification tray does not change when a hotkey is used to apply a profile

### ISSUE THREAD

**Issue by skst** [Belphemur/SoundSwitch#450] opened 2020-05-18 19:16 UTC
**Describe the bug**
When changing the profile with a hotkey, the notification icon does not change to the icon specified in the profile.

**Version**
SoundSwitch v5.0.4.31153

**To Reproduce**
~~1. I create two profiles ("A" and "B"), each with different hotkeys and _Playback_ and _Recording_ icons. Profile A is my current configuration.
2. In _Settings_, I set **Systray Icon** to _Playback_.
3. Note: the notification icon is the one for profile A.
4. I use one of the hotkeys to change to profile B.
5. Bug: The notification icon does not change to show the _Playback_ icon for profile B. (It still shows the _Playback_ icon for profile A.)~~
1. I create two profiles ("A" and "B"), each with different hotkeys and _Playback_ and _Recording_ icons. Profile A is my current configuration. Profile B has different playback and recording devices.
2. In _Settings_, I set **Systray Icon** to _Playback_.
3. Note: the notification icon is the one for profile A.
4. I use the hotkey to change to profile B.
5. The notification icon changes to show the _Playback_ icon for profile B.
6. I use the hotkey to change to profile A.
7. Bug: The notification icon does not change to show the _Playback_ icon for profile A. (It still shows the _Playback_ icon for profile B.)

**Expected behavior**
The notification icon should show the _Playback_ icon for profile B when profile B is active.

**Screenshots**
I've attached three screenshots to show the profiles, _Normal_ profile (correct icon), and _Headset_ profile (incorrect icon).
![Profiles](https://user-images.githubusercontent.com/74487/82250833-d11c2d80-9911-11ea-8612-90592f2f765d.png)
![Normal](https://user-images.githubusercontent.com/74487/82250843-d4171e00-9911-11ea-9731-50ba36303fee.png)
![Headset](https://user-images.githubusercontent.com/74487/82250838-d24d5a80-9911-11ea-99c6-4bf314932653.png)

**Comment by Belphemur** [comment] 2020-05-18 21:08
Hello @skst,

I'm not able to reproduce your issue.
![issue-450](https://user-images.githubusercontent.com/197810/82259747-13516900-992a-11ea-8e57-91fdd2d32fb2.gif)

For me the icon does change when I change the profile.
Do you see a notification telling you the device changed ?

**Comment by skst** [comment] 2020-05-18 21:16
Hmm. Yes, I do see the banner telling me the profile changed. Here are screenshots of my Settings (in case that's relevant) and the banner.
![banner](https://user-images.githubusercontent.com/74487/82260466-eea5c300-9922-11ea-8b66-84735c812741.png)
![Settings](https://user-images.githubusercontent.com/74487/82260471-efd6f000-9922-11ea-8c15-3cbb955389f3.png)

**Comment by skst** [comment] 2020-05-20 20:17
I've noticed that, after restarting Windows, the icon changes the _first_ time I switch to a profile using a hotkey. After that, however, it does not change when I change profiles.

Of course, I can't guarantee that something else isn't affecting it, but I hope this helps.

**Comment by Belphemur** [comment] 2020-05-21 23:52
I'm sorry it's hard to understand what is exactly happening ...

Do you have that issue with other dynamic systray icons ?

**Comment by skst** [comment] 2020-05-22 03:47
Sorry. I'll endeavor to clarify.

1. I create two profiles ("A" and "B"), each with different hotkeys and _Playback_ and _Recording_ icons. Profile A is my current configuration. Profile B has different playback and recording devices.
2. In _Settings_, I set **Systray Icon** to _Playback_.
3. Note: the notification icon is the one for profile A.
4. I use the hotkey to change to profile B.
5. The notification icon changes to show the _Playback_ icon for profile B.
6. I use the hotkey to change to profile A.
7. Bug: The notification icon does not change to show the _Playback_ icon for profile A. (It still shows the _Playback_ icon for profile B.)

(I've also updated the original post.)

**Comment by Belphemur** [comment] 2020-05-23 14:49
This is the exact scenario I've tested ...
I'm not able to reproduce neither understand what is happening on your machine ...

**Comment by skst** [comment] 2020-05-23 17:15
If I haven't made it clear what's happening on my machine, you probably haven't been able to test the exact scenario. 🙂

Can you tell me which of my steps to reproduce the issue aren't clear so that I can try to improve how I'm describing the issue?

**Summary:** The notification icon changes only the first time that I use a hotkey to change the profile. After that, the notification icon never changes again.

**Comment by Belphemur** [comment] 2020-05-31 15:20
Can you try with v5.3.0

Not sure it will fix your issue, but since there has been some changes to the profile feature and to the core of the app, it might.

**Comment by skst** [comment] 2020-05-31 17:21
I installed 5.3.0 over my previous install. The notification icon does not change when I use a profile hotkey.

**Comment by Belphemur** [comment] 2020-05-31 17:59
Is it possible that both your device have the same small icon? 

Can you change the icon of one of the two device by going into Windows settings? 

Right click on SoundSwitch > Playback devices > right click on the device > properties 

And select a different icon :) 

Sent from Nine
________________________________

**Comment by skst** [comment] 2020-05-31 21:12
A good thought, but sadly, that's not the case. In addition to the screenshots I provided in the OP showing the icons in the profiles which are the ones that SoundSwitch displays in the banners and for the notification icon, here are the icons of the playback devices themselves.

![Untitled](https://user-images.githubusercontent.com/74487/83362761-4dbefb00-a359-11ea-8852-1b46e679c1b4.png)

**Comment by Belphemur** [comment] 2020-05-31 21:29
Did you change one of them? 

Even if the big icon look this way, it doesn't mean the small one will too. 

I had that issue before with official windows icons. 

Sent from Nine
________________________________

**Comment by skst** [comment] 2020-05-31 21:35
Absolutely, icons can have different images for different sizes. But, yes, I changed the headset icon just in case and, no, it didn't change. You know better than I do, but it appears that those aren't the icons that SoundSwitch uses since the "speakers" icon doesn't match the one SoundSwitch lists in the profile.

**Comment by Belphemur** [comment] 2020-06-01 14:59
It does use that icon, but there is a cache in place. It won't change if the icon is currently in use.

If you have the settings open when changing the icon, the change won't be reflected until you reopen the settings.

I admit, I'm not able to understand what isn't working in your setup ...

Last idea, can you download and assign this icon to one of the two device ?
https://soundswitch.aaflalo.me/favicon.ico

Then do the profile switching.

**Comment by skst** [comment] 2020-06-01 17:24
I don't have the system settings nor the SoundSwitch settings open when I change profiles. I also don't think I ever changed the system icon. Please note that the icons shown for the SoundSwitch profiles match the system icons, however the icon shown in the notification area does not match any of them.

I assigned the icon to the _Speakers_ device. I used the hotkey to change to the **Headset** profile. The icon didn't change. I used the hotkey to change to the **Normal** profile (with the _Speakers_ device). The icon didn't change.

**Comment by amerker** [comment] 2021-03-18 16:00
I have the same issue, after setting up SoundSwitch on a new PC.
SoundSwitch 5.7.2.29590, Win 10 Pro 20H2.

The problem is related only to the Playback devices, and it's most obvious when I have Systray Icon set to "Playback".
It correctly switches if "Recording" or "Both" is selected, though in the latter case I can only see the recording device switching.

The icons of the Playback devices themselves are fine and distinct, as I can see when switching directly via the Ctrl-Alt-F11 hotkey.

The workaround for me right now is that I keep it set to Both and simply benefit from both Recording devices in my profiles having different icons.

**Comment by mrgoodwin** [comment] 2021-08-02 06:55
I can confirm the exact behavior @amerker describes. I have two profiles configured. One that uses my speakers for playback and my webcam for recording. The other profile uses my headset for both playback and recording. I have a hotkey assigned to each profile. I have distinct icons set for each device in Windows Sound Settings and SoundSwitch is set to display the Playback icon in the notification area,

When I use the global Ctrl-Alt-F11 hotkey to cycle through playback devices, the system tray icon updates to show the correct playback device. If I use the left-click menu to select a playback device, the system tray icon updates correctly as well.

But if I trigger either of my profiles (type of trigger doesn't seem to matter) the system tray icon does not update. It just stays with whatever icon it was showing before. 

SoundSwitch Stable 5.11.2.39643 Win 10 Pro 20H2, also a new PC and a fresh install of SoundSwitch. What's really frustrating is this was working just fine on my old system.

**Comment by Belphemur** [comment] 2021-10-13 00:56
I think I might have found the issue with this one.

Can you check with v6.1.2 if it's fixed ?

**Comment by skst** [comment] 2021-10-13 04:19
Sorry, no. It's still an issue in 6.1.2.0.

**Comment by Belphemur** [comment] 2021-10-13 22:51
@skst Can you join me on Discord, I have a beta version with better logs to try to understand what is happening here.

Discord:
https://discord.gg/gUCw3Ue

Link of the beta:
https://f000.backblazeb2.com/file/SoundSwitch/nightly/SoundSwitch-dev.zip

**Closed** 2021-10-14 02:48 UTC
Labels: Bug
