### ISSUE TITLE
Would be useful: the tray popup menu displays the profiles

### ISSUE THREAD

**Issue by schittli** [Belphemur/SoundSwitch#621] opened 2021-05-02 08:45 UTC
**Is your feature request related to a problem? Please describe.**

The profiles are **very** useful, but for me, the triggers almost never fit: I change profiles based on the situation / depending on where I am: 
* Am I at home and have the hi-fi connected?
* Would now be better to use the headset because I'm not alone in the room?
* Am I at work and have a conference-cam connected?
* …

At the same time, it would also be great to be able to assign hotkeys to two new functions:

* Hotkey for: Switch to the next profile
* Hotkey for: Switch to the previous profile

If the active playback/record devices do not match a profile, the two functions would simply start with the first profile, for example :-) 

**Describe the solution you'd like**

The popup menu could look like this:

![image](https://user-images.githubusercontent.com/8282673/116807024-222c2e00-ab31-11eb-8589-1214df7232bd.png)

It would probably have this logic:

1. If the user directly selects a device 
2. and the playback/recording combination matches a profile, 
3. then the profile will be marked with a ✔️ 
4. Otherwise the profile has no  ✔️

**Describe alternatives you've considered**
I already have noted all of them :-)

**Additional context**
See above :-)

Thanks a lot, kind regards,
Thomas

**Comment by Belphemur** [comment] 2021-05-02 14:11
Hello,

This is already implemented in v5.9.0 that I released yesterday :)

Also duplicate of issue #492.

I don't plan to add which profile is currently active as technically you could have multiple ones at the same time since a profile is applicable to a single application.

**Closed by Belphemur** 2021-05-02 14:11 UTC
Labels: Enhancement
