### ISSUE TITLE
Crash after booting up PC: When using Profile feature and the audio device isn't connected

### ISSUE THREAD

**Issue by cypressious** [Belphemur/SoundSwitch#457] opened 2020-05-28 07:39 UTC
The app crashed right after booting up the PC. It created the following log file:

[SoundSwitch-crashlog-28_5_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4694000/SoundSwitch-crashlog-28_5_2020.zip)

**Comment by CS-5** [comment] 2020-05-28 12:49
Are you running Windows 10 2004? 

I just updated and the app does not crash on boot, but it does crash when switching sound profiles. I'm going to guess an incompatibility with this version of windows.

[SoundSwitch-crashlog-28_5_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4695574/SoundSwitch-crashlog-28_5_2020.zip)

**Comment by Belphemur** [comment] 2020-05-28 13:31
@cypressious & @CS-5 

It's related to the profile feature.
* You have some profile setup with hotkey
* PC Start
* You use the hotkey
* The configured device is not connected/available.
* SoundSwitch crash

SoundSwitch made assumption that the device would be present when triggering the hotkey.

It's a bug, unrelated to the version of Windows.

**Comment by cypressious** [comment] 2020-05-28 14:01
Actually I didn't press a button. I turned on the PC went away and when I
came back, I was greeted by the crash.

Kirill Rakhman

Antoine Aflalo <notifications@github.com> schrieb am Do., 28. Mai 2020,
15:31:

**Comment by Belphemur** [comment] 2020-05-28 17:49
@cypressious My bad, I've actually checked the wrong log file...

Actually, this is a duplicate of #455 

It will be fixed as soon as a release a new version ...

**Closed by Belphemur** 2020-05-28 17:49 UTC
Labels: Bug, Confirmed
