### ISSUE TITLE
Auto Updater is Crashing on v4.15.*

### ISSUE THREAD

**Issue by sdgsdfhdxftghjcfgjgfcdhjdgfyjgfhjfghjfc** [Belphemur/SoundSwitch#376] opened 2019-11-24 21:54 UTC
I am on Windows Insider.
Everything worked well up to a couple of weeks ago.
Now: Every time I log in to Windows I have to right click settings and choose devices.
Now: Every update attempt fails majorly.
[kukenballentjongavallen.txt](https://github.com/Belphemur/SoundSwitch/files/3884182/kukenballentjongavallen.txt)

**Comment by Belphemur** [comment] 2019-11-24 22:02
Hello, 

I'm sorry to hear that. 

Unfortunately you'll have to update manually to the latest version. 

The bug you're encounter has been fixed in v4.16.1

________________________________

**Comment by Akito13** [comment] 2019-11-25 11:41
Same here.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   at SoundSwitch.UI.UserControls.ChangelogWebViewer..ctor()
   at SoundSwitch.UI.Forms.UpdateDownloadForm.InitializeComponent() in D:\VS\SoundSwitch\SoundSwitch\UI\Forms\UpdateDownloadForm.Designer.cs:line 37
   at SoundSwitch.UI.Forms.UpdateDownloadForm..ctor(Release release) in D:\VS\SoundSwitch\SoundSwitch\UI\Forms\UpdateDownloadForm.cs:line 37
   at SoundSwitch.Util.TrayIcon.OnUpdateClick(Object sender, EventArgs eventArgs) in D:\VS\SoundSwitch\SoundSwitch\Util\TrayIcon.cs:line 210
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SoundSwitch
    Assembly Version: 4.15.1.37703
    Win32 Version: 4.15.1.37703
    CodeBase: file:///C:/Program%20Files/SoundSwitch/SoundSwitch.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
NAudio
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/NAudio.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/Serilog.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.3.3
    Win32 Version: 1.1.3.3
    CodeBase: file:///C:/Program%20Files/SoundSwitch/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Program%20Files/SoundSwitch/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Serilog.Enrichers.Thread
    Assembly Version: 2.0.0.0
    Win32 Version: 3.1.0.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/Serilog.Enrichers.Thread.DLL
----------------------------------------
Serilog.Enrichers.Environment
    Assembly Version: 2.0.0.0
    Win32 Version: 2.1.3.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/Serilog.Enrichers.Environment.DLL
----------------------------------------
Serilog.Exceptions
    Assembly Version: 5.3.1.0
    Win32 Version: 5.3.1.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/Serilog.Exceptions.DLL
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 2.0.0.0
    Win32 Version: 4.1.0.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/Serilog.Sinks.File.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SoundSwitch.Audio.Manager
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/SoundSwitch.Audio.Manager.DLL
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
SoundSwitch.UI.UserControls
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/SoundSwitch/SoundSwitch.UI.UserControls.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

@Belphemur The problem is, this happens when trying to update. Then the program crashes. You need to make an announcement, so people who never heard of _Github_ or _Software Development_ will know that they need to manually download a new version and install it.

**Comment by ramime** [comment] 2019-11-25 17:54
Same problem here. Then I downloaded V4.16.1.16453_Release_Installer.exe and got a virus Warning from Windows Defender SmartScreen, which I'm not willing to ignore (see attached screenshot)
![Soundswitch Virus Warning](https://user-images.githubusercontent.com/1032567/69565281-f3fa0480-0fb4-11ea-935d-4096bafc4dd9.png)

**Comment by Akito13** [comment] 2019-11-25 18:12
@ramime 
Disable all Windows-native programs, including _Windows Defender_. It creates panic for no reason. You can even see that being admitted by the warning, as it only complains about an "Unkown Issuer". Yes, of course some open source project among the millions other on Github doesn't need to be known by Microsoft, personally.

I downloaded the newest update, installed it and my computer still is alive. 🎉 

If you are paranoid on a psychotic level, you are welcome to compile the software yourself.

P.S.: If you don't trust shady software, stop using Windows.

**Comment by Belphemur** [comment] 2019-11-25 19:22
I'm trying to see if I can get an official Code Signing certificate validated by Windows.

Once done, those kinds of stupid warnings will go away. In the meantime, all I can tell you is SoundSwitch never had any kind of malware/adware/spyware/etc ...

I also publish each version with its virus total scan to prove it.
It's up to you to trust me or not.

**Comment by edofthefu** [comment] 2019-11-25 21:18
I have the same issue:

* I had a perfectly functioning SoundSwitch that told me I had to update
* I updated, which immediately broke it in every way
* I came to the GitHub page, only to find that now I have to download a new executable that Windows tells me is dangerous, and which also doesn't have a clean VirusTotal scan.
* I cannot find older versions of the executables to reinstall the working versions of SoundSwitch

Surely you can appreciate that this is a somewhat frustrating and concerning experience for the user.

**Comment by Akito13** [comment] 2019-11-25 21:27
@edofthefu Just install the newest version and disable all Windows-native software, which is the reason for your frustration. The binary is safe.

If you want to reduce frustration, remove Microsoft Windows.

**Comment by Belphemur** [comment] 2019-11-25 22:54
@edofthefu You'll have the exact message from Windows for any version of SoundSwitch because I'm self-signing them. (Proof that it did come from me and not anybody else, the updater check that also).

Windows 10 in the latest version decided to enforce their SmartScreen (not really useful as it doesn't block real threats).

The different antivirus that are detection SoundSwitch as a risk are unknown, insignificant ones and false positive.

You can try yourself, you have here all the releases of SoundSwitch: 
https://github.com/Belphemur/SoundSwitch/releases

**Comment by ramime** [comment] 2019-11-25 23:08
I've now uninstalled the (I think v4.15.1) and let it clear all settings on uninstall.
Then I downloaded v4.14.0.31865 and installed it. 
I've got _no_ virus warning(!) on this older version and it works perfect as before. 
This will be my way to go.

I really like the program and I've already donated for it, but I don't like the Windows-Bashing, since this is a program only for windows!

**Comment by Belphemur** [comment] 2019-11-25 23:23
@ramine I understand, I'm only unhappy with the way SmartScreen works.


Anyway, as said, I have ordered a valid certificate from [Certum](https://en.sklep.certum.pl/open-source-code-signing.html), I need to wait for them to send me the Card Reader then I'll be able to generate the cert and sign SoundSwitch with it.

This way, there shouldn't be any more issue with SmartScreen.

**Comment by ramime** [comment] 2019-11-25 23:26
@Belphemur I'm not sure if the certificate is the problem. Version v4.14.0 don't bother the SmartScreen!?

**Comment by Belphemur** [comment] 2019-11-25 23:30
@ramine That is indeed weird ...
Between the v4.14 and v4.16 I've updated InnoSetup (the installer builder) to the latest version. That is the only change I see that could cause issues.

What happens if you try the other versions like v4.15.1 ? Does SmartScreen comes up ?

**Comment by Belphemur** [comment] 2019-11-26 00:25
@ramime It was the version v6.0.3 of InnoSetup that was making the installer being detected as virus by SmartScreen.

I've updated the installer of v4.16.1 : https://github.com/Belphemur/SoundSwitch/releases/download/v4.16.1/SoundSwitch_v4.16.1.34861_Release_Installer.exe

Also VirusTotal is happy now: https://www.virustotal.com/gui/file-analysis/ZGNkMzEwYWM1NTczODRlMDcyMTUwNTk3OTM5ZDM0MmM6MTU3NDcyNzc4NQ==/detection

**Comment by FireEmerald** [comment] 2019-11-26 06:27
By the way, i don't think that a Open Source Code certificate from Certum would delete any SmartScreen messages, as it is described here:
![2019-11-26 07_24_26-Window](https://user-images.githubusercontent.com/1107939/69604506-f8a6d300-101d-11ea-9531-8fe4c09341b0.png)
Or you bought the EV version which costs 359€ 🤣 ... i don't think so.

**Comment by ramime** [comment] 2019-11-26 06:55
@Belphemur 
I've now downloaded und opened the following versions from https://github.com/Belphemur/SoundSwitch/releases:
SoundSwitch_v4.16.2.36561_Beta_Installer.exe  -> SmartScreen
SoundSwitch_v4.16.1.34861_Release_Installer.exe -> SmartScreen
SoundSwitch_v4.16.0.41017_Release_Installer.exe -> SmartScreen
SoundSwitch_v4.15.1.37703_Release_Installer.exe -> SmartScreen
SoundSwitch_v4.15.0.40592_Release_Installer.exe -> SmartScreen
SoundSwitch_v4.14.0.31865_Release_Installer.exe -> SmartScreen now(!?). Yesterday it doesn't trigger on this version!?
I have the SoundSwitch_v4.14.0.31865_Release_Installer.exe downloaded yesterday still in my downloads and this version doesn't trigger SmartScreen but the version I downloaded today does!?

Very strange!

I think SmartScreen is learning the false positive, which would be very bad!?

**Comment by Akito13** [comment] 2019-11-26 12:14
> I think SmartScreen is learning the false positive, which would be very bad!?

That is what most so-called "Anti-Virus" software does nowadays. They detect a potentially harmful pattern, then they save it and "remember" it the next time something of that type is scanned.

The problem now clearly is on Microsoft's side.

**Comment by Akito13** [comment] 2019-11-26 12:17
> Or you bought the EV version which costs 359€ 🤣 ... i don't think so.

Strong indication, that SmartScreen is there to generate more profit for Microsoft. If you can force so many developers/publishers of software to buy such a licence, you can make huge profits just by creating a superficial threat message, that in reality has nothing to say.

**Comment by Belphemur** [comment] 2019-11-26 12:42
We'll see with the certificate. 

Because with it, I won't have to pack my own CA cert in the installer. (the Trust SoundSwitch certificate). 

I guess even have that as opt-in is considered dangerous now by Microsoft.

For now, I'm stuck until I have it... All I can do is ask you to ignore it... Or to install a real anti-virus like Eset. 

I didn't find a way to report false positive... While every other anti-virus does have a way. 

I'm just crossing finger that the cert will resolve everything... 
________________________________

**Comment by Akito13** [comment] 2019-12-03 04:12
# Update
I installed the newest update and my PC still is not broken! I'm waiting for the virus, where is it? 
 ![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSZHFb4Px56sC5kXGGgk_anFno5Q3JtzOu-KJhkbJvjq0HzgvsRg&s)

**Comment by Belphemur** [comment] 2019-12-12 22:45
Just to give an update: I'm going through Centrum Identity verification.
I should get the certificate in a week or so (I hope).

**Comment by Belphemur** [comment] 2019-12-14 02:05
There you go.

v4.16.3 is the first version with an official signature.

**Closed** 2020-04-03 17:10 UTC
Labels: Bug, Confirmed
