### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by DhrRob** [Belphemur/SoundSwitch#21] opened 2015-08-29 01:49 UTC
Currently whenever I start the application, I can select the audio devices that I'd like to switch between, I press closed and nothing happens. If I use the hotkey I get the error that no devices are available to switch to.

Win 10 x64 (Education)

Event Viewer error:
03:45:06.322 WindowsAPIAdapter SoundSwitch+TrayIcon.<SetEventHandlers>b__10_0 No devices available

**Comment by MountainDeux** [comment] 2015-08-29 03:57
I am having the exact same problem in Windows 10. I can set the hot key but the device selections do not seem to stick

**Comment by Belphemur** [comment] 2015-08-29 05:05
Are the sound card you checked still checked in the setting menu when you're reopening it? 

Can you copy/paste the content of %appdata%\SoundSwitch\SoundSwitchConfiguration.json? 

Since the settings is showing all the installed sound card (not only the one active) it's possible you selected only the one that aren't active. 

On 29 August 2015 06:57:27 EEST, MountainDeux <notifications@github.com> wrote:
>I am having the exact same problem in Windows 10. I can set the hot key
>but the device selections do not seem to stick
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/21#issuecomment-135937500

-- 
Best Regards, 
Antoine Aflalo

**Closed** 2015-08-29 07:50 UTC
Labels: bug, Confirmed

**Comment by Belphemur** [comment] 2015-08-29 07:56
Please try the new release Isabelline Gold Oyster (3.3.1). It should resolve this annoying issue.

**Comment by MountainDeux** [comment] 2015-08-29 13:09
Thanks! I can confirm the latest release worked for me. I ended up doing a manual install, would the auto update have worked too?

**Comment by Belphemur** [comment] 2015-08-29 14:15
Yes,  the bug wasn't affecting the auto update. 

On 29 August 2015 16:09:33 EEST, Tyson Navarre <notifications@github.com> wrote:
>Thanks! I can confirm the latest release worked for me. I ended up
>doing a manual install, would the auto update have worked too?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/21#issuecomment-135983991

-- 
Best Regards, 
Antoine Aflalo
