### ISSUE TITLE
When switching the Systray Icon to Recording mode

### ISSUE THREAD

**Issue by fatrolls** [Belphemur/SoundSwitch#533] opened 2021-01-07 01:29 UTC
**What were you doing when it crashed ?**
When switching the Systray Icon to Recording mode

**To Reproduce**
1. Go to Settings
2. Click on SystrayIcon dropdown combobox
3. Scroll down to Recording

```
[15:51:41.259 FTL] Exception Occurred  (at SoundSwitch.Program.HandleException)
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at SoundSwitch.Framework.TrayIcon.Icon.Changer.RecordingIconChanger.ChangeIcon(TrayIcon trayIcon) in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Framework\TrayIcon\Icon\Changer\RecordingIconChanger.cs:line 20
   at SoundSwitch.UI.Forms.SettingsForm.iconChangeChoicesComboBox_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\UI\Forms\Settings.cs:line 693
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

But it does't actually crash the program maybe a silent Try/Catch Exception will solve this problem.. I think it's because I don't have a recording mic or something. hooked up to my computer

**ZIP**
[SoundSwitch-crashlog-7_1_2021.zip](https://github.com/Belphemur/SoundSwitch/files/5779001/SoundSwitch-crashlog-7_1_2021.zip)

**Comment by Belphemur** [comment] 2021-01-09 17:39
Hello,

Thanks for the report, duplicate of #530 (even if this one is actually a more detailed report).

Will be fixed in next version.

**Closed by Belphemur** 2021-01-09 17:39 UTC
Labels: Bug-Crash, Confirmed, Invalid-Duplicate
