### ISSUE TITLE
Win modifier for shortcut

### ISSUE THREAD

**Issue by gufpewga** [Belphemur/SoundSwitch#535] opened 2021-01-12 17:59 UTC
Hello,
Could you allow Win key to be used as modifier?
I would like to use Win + C as shortcut. I disables Cortana so this shortcut is free.
But if I try to put Win key it's red and doesn't work.
I'm on latest verson to this date.

**Comment by Belphemur** [comment] 2021-01-12 20:01
Duplicate of #534

**Closed** 2021-01-12 20:01 UTC
Labels: Enhancement
