### ISSUE TITLE
Installation crashes at .NET Core 3.1.4 since Update from Microsoft

### ISSUE THREAD

**Issue by Amasov** [Belphemur/SoundSwitch#479] opened 2020-06-20 07:43 UTC
The Installation in latest Version (5.4.0.34051) crashes at .NET Core 3.1.4 since Microsoft updated to .NET Core 3.1.5 (assumingly on 09th of June 2020 (Rollout 13th of June 2020)), this was an automatic Update.

An Installation of .NET SDK 3.1.301 did not affect the behavior.

**Dependencies:**

![grafik](https://user-images.githubusercontent.com/11898994/85196328-c6223780-b2d9-11ea-9e0f-83c6265e3424.png)

**Download:**

![grafik](https://user-images.githubusercontent.com/11898994/85196332-d508ea00-b2d9-11ea-9db6-c11cd0ab9523.png)

**Error:**

![grafik](https://user-images.githubusercontent.com/11898994/85196336-df2ae880-b2d9-11ea-9976-82404a1fa699.png)

Since I dont know the location of the related Installer-Logfiles, I cant post them. Please advise for the location of the logs.

Kind regards.

**Comment by Amasov** [comment] 2020-06-20 08:04
Found it:

[0E9C:0F50][2020-06-20T09:11:15]i001: Burn v3.10.4.4718, Windows v10.0 (Build 18363: Service Pack 0), path: C:\WINDOWS\Temp\{9030A53A-AFA1-40F3-8ECC-BE9F5AD95933}\.cr\windowsdesktop-runtime-3.1.4.exe
[0E9C:0F50][2020-06-20T09:11:15]i000: Initializing string variable 'DOTNETHOME' to value '[ProgramFiles64Folder]dotnet'
[0E9C:0F50][2020-06-20T09:11:15]i000: Initializing string variable 'BUNDLEMONIKER' to value 'Microsoft Windows Desktop Runtime - 3.1.4 (x64)'
[0E9C:0F50][2020-06-20T09:11:15]i000: Initializing string variable 'PRODUCT_NAME' to value 'Microsoft Windows Desktop Runtime - 3.1.4 (x64)'
[0E9C:0F50][2020-06-20T09:11:15]i000: Initializing string variable 'LINK_PREREQ_PAGE' to value 'https://go.microsoft.com/fwlink/?linkid=846817'
[0E9C:0F50][2020-06-20T09:11:15]i009: Command Line: '-burn.clean.room=C:\Users\Chris\AppData\Local\Temp\is-PPK4H.tmp\windowsdesktop-runtime-3.1.4.exe -burn.filehandle.attached=620 -burn.filehandle.self=632 /lcid 1031 /passive /norestart /showrmui'
[0E9C:0F50][2020-06-20T09:11:15]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\Chris\AppData\Local\Temp\is-PPK4H.tmp\windowsdesktop-runtime-3.1.4.exe'
[0E9C:0F50][2020-06-20T09:11:15]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\Chris\AppData\Local\Temp\is-PPK4H.tmp\'
[0E9C:0F50][2020-06-20T09:11:15]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\Chris\AppData\Local\Temp\Microsoft_Windows_Desktop_Runtime_-_3.1.4_(x64)_20200620091115.log'
[0E9C:0F50][2020-06-20T09:11:15]i000: Setting string variable 'WixBundleName' to value 'Microsoft Windows Desktop Runtime - 3.1.4 (x64)'
[0E9C:0F50][2020-06-20T09:11:15]i000: Setting string variable 'WixBundleManufacturer' to value 'Microsoft Corporation'
[0E9C:2898][2020-06-20T09:11:15]i000: Setting numeric variable 'WixStdBALanguageId' to value 1033
[0E9C:2898][2020-06-20T09:11:15]i000: Setting version variable 'WixBundleFileVersion' to value '3.1.4.28821'
[0E9C:0F50][2020-06-20T09:11:15]i100: Detect begin, 4 packages
[0E9C:0F50][2020-06-20T09:11:15]i102: Detected related bundle: {22d43cf1-98d2-4a06-9624-36cadfdeb74a}, type: Upgrade, scope: PerMachine, version: 3.1.5.28920, operation: Downgrade
[0E9C:0F50][2020-06-20T09:11:15]i101: Detected package: windowsdesktop_runtime_3.1.4_win_x64.msi, state: Absent, cached: None
[0E9C:0F50][2020-06-20T09:11:15]i101: Detected package: dotnet_runtime_3.1.4_win_x64.msi, state: Absent, cached: None
[0E9C:0F50][2020-06-20T09:11:15]i101: Detected package: dotnet_hostfxr_3.1.4_win_x64.msi, state: Absent, cached: None
[0E9C:0F50][2020-06-20T09:11:15]i101: Detected package: dotnet_host_3.1.4_win_x64.msi, state: Absent, cached: None
[0E9C:0F50][2020-06-20T09:11:15]i052: Condition '((VersionNT > v6.1) OR (VersionNT = v6.1 AND ServicePackLevel >= 1))' evaluates to true.
[0E9C:0F50][2020-06-20T09:11:15]i052: Condition 'VersionNT64' evaluates to true.
[0E9C:0F50][2020-06-20T09:11:15]i199: Detect complete, result: 0x0
[0E9C:2898][2020-06-20T09:11:15]e000: Error 0x80070666: Cannot install a product when a newer version is installed.
[0E9C:0F50][2020-06-20T09:11:15]i500: Shutting down, exit code: 0x666

**Comment by Belphemur** [comment] 2020-06-20 13:49
Here is an updated version of the installer that detect 3.1.5 as a valid version.
[SoundSwitch_v5.4.0.17624_Release_Installer.exe.zip](https://github.com/Belphemur/SoundSwitch/files/4807971/SoundSwitch_v5.4.0.17624_Release_Installer.exe.zip)

**Comment by Belphemur** [comment] 2020-06-20 13:50
It's a duplicate of : https://github.com/Belphemur/SoundSwitch/issues/474

**Closed by Belphemur** 2020-06-20 13:50 UTC
Labels: Bug, Invalid-Duplicate

**Comment by Amasov** [comment] 2020-06-21 13:29
> 
> 
> Here is an updated version of the installer that detect 3.1.5 as a valid version.
> [SoundSwitch_v5.4.0.17624_Release_Installer.exe.zip](https://github.com/Belphemur/SoundSwitch/files/4807971/SoundSwitch_v5.4.0.17624_Release_Installer.exe.zip)

Hey thanks, but this one also do not recognize .NET Core 3.1.5 as valid. The installer still tries to install 3.1.4

Sorry
