### ISSUE TITLE
Crashing every time

### ISSUE THREAD

**Issue by asherbasher** [Belphemur/SoundSwitch#165] opened 2017-03-12 14:34 UTC
Tried reinstalling but it just crashes every time it launches. I've previously used this program for years with no issues other than the occasional crash but just today started having this issue.

[SoundSwitch-crashlog-12_3_2017](https://ufile.io/5cb181)

Wouldn't let me attach a file either so I've uploaded it.

**Comment by asherbasher** [comment] 2017-03-12 14:39
Fixed by deleting the SoundSwitchConfiguration.json file. Not sure what caused this to start happening though as I hadn't changed any settings and I don't have any notifications enabled for it.

**Comment by FireEmerald** [comment] 2017-03-12 15:34
This is a known bug introduced in the beta 3.13.0 and fixed in the latest release 3.13.1.
The changelog of 3.13.1 contains the following warning:

> ### Warning for Beta Users
> If you are coming from the previous Beta version, it's possible your settings will be messed up for the Notification or even crash on Windows 7. Please delete your configuration located in %appdata%/SoundSwitch then restart SoundSwitch. This is not applicable for the users on the Stable channel (the default setting).

Duplicate of #161.

**Closed** 2017-03-12 16:23 UTC
Labels: Confirmed, duplicate
