### ISSUE TITLE
Program keeps crashing if notification setting is set to "Customized Sound Notification" and no sound file is chosen. 

### ISSUE THREAD

**Issue by Oupi** [Belphemur/SoundSwitch#177] opened 2017-03-29 18:01 UTC
Program keeps crashing if notification setting is set to "Customized Sound Notification" and no sound file is chosen for example clicking "cancel" in the selecting window. Sole reinstall doesn't help. One must delete associated %appdata% files to reset settings. Another workaround to get it work without reinstalling is to modify "SoundSwitchConfiguration.json" file found from %appdata%. In the file changing the "NotificationSettings" to something else than 3 helped.
Here's crashlog: [SoundSwitch-crashlog-29_3_2017.zip](https://github.com/Belphemur/SoundSwitch/files/879915/SoundSwitch-crashlog-29_3_2017.zip)

**Comment by FireEmerald** [comment] 2017-03-29 19:05
**Duplicate of #175.**

**Closed** 2017-03-30 00:35 UTC
Labels: duplicate
