### ISSUE TITLE
Bluetooth Speakers Not Shown

### ISSUE THREAD

**Issue by McFirn** [Belphemur/SoundSwitch#362] opened 2019-11-13 01:49 UTC
The newest version, 4.15.0.40592, does not display my Bluetooth speakers, even though they are connected, and it shows them as the active device in the SoundSwitch hover tooltip when they are set as default. The only device shown when I click on the toolbar icon is my headset. Both devices are checked in the Settings -> Playback tab.

The previous version I had installed showed both devices correctly.

**Comment by Belphemur** [comment] 2019-11-13 01:58
Duplicate of #360 

Will be fixed in latest version.

**Closed** 2019-11-13 01:57 UTC
