### ISSUE TITLE
Crash on open update details when ussing Classic Windows theme

### ISSUE THREAD

**Issue by JustOff** [Belphemur/SoundSwitch#220] opened 2017-11-21 10:47 UTC
I had 3.15.1 installed with "Notify me when updates are available" setting. Today I received notification about 3.15.2, but when trying to see the details SoundSwitch has been crashed. I restarted it, but the result was the same. The only way to get a new version was to change update settings to "Install automatically".

PS: Sorry, but I'm not comfortable with exposing crashdumps publicly.

**Comment by Belphemur** [comment] 2017-11-21 14:22
Hello,

Without the crashlog I can't help you.

Can you send it to me using my contact form ?

https://www.aaflalo.me/contact/

**Comment by JustOff** [comment] 2017-11-21 15:07
I tried both Chrome & Firefox, but send is never ending and console reports `jquery.js?ver=1.12.4:4 POST https://www.aaflalo.me/wp-json/contact-form-7/v1/contact-forms/665/feedback 413 ()`.

**Comment by Belphemur** [comment] 2017-11-21 15:19
In that case send it directly to:

antoine{at}aaflalo{dot}me

**Comment by JustOff** [comment] 2017-11-21 15:45
Done.

**Comment by Belphemur** [comment] 2017-11-21 15:54
About the contact form, I didn't expect the file to be more than 10MB. This is correct for further usage.

About your issue, it's a duplicate of #194 which was resolved by @FireEmerald in #195 

It's weird to see it coming back. Can you confirm that you're using the Classic Windows theme ?
```
Message: Visual Styles-related operation resulted in an error because no visual style is currently active.
Source: System.Windows.Forms
StackTrace:
   at System.Windows.Forms.VisualStyles.VisualStyleRenderer.IsCombinationDefined(String className, Int32 part)
   at System.Windows.Forms.VisualStyles.VisualStyleRenderer..ctor(String className, Int32 part, Int32 state)
   at System.Windows.Forms.ProgressBarRenderer.InitializeRenderer(VisualStyleElement element)
   at System.Windows.Forms.ProgressBarRenderer.DrawHorizontalBar(Graphics g, Rectangle bounds)
   at SoundSwitch.UI.UserControls.TextProgressBar.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by JustOff** [comment] 2017-11-21 15:55
> Can you confirm that you're using the Classic Windows theme ?

Yes.

**Comment by Belphemur** [comment] 2017-11-21 16:07
Do you mind if I share your dump with @FireEmerald  ?

**Comment by JustOff** [comment] 2017-11-21 16:08
Of course, just not expose it to the public, plz. Thank you in advance.

**Comment by FireEmerald** [comment] 2017-11-23 09:50
I don't like the current update process at all. There are free frameworks like https://github.com/ProgTrade/nUpdate which could be implemented instead of re-implementing the wheel.

**Comment by Belphemur** [comment] 2017-11-23 22:43
@FireEmerald That would be nice feature to have to start the 4.0.0

Would you like to explore the possibility to use that lib to redo the update process?

**Comment by FireEmerald** [comment] 2017-11-24 15:32
I already evaluated the lib several month ago but for the rest of 2017 i will be unable to implement this, due to less free time. Perhaps in the winter holidays...

**Comment by Belphemur** [comment] 2017-11-24 15:44
Sure I understand.

Let's keep it as an open improvement :)

It will be for 4.1 instead of 4.0.

**Comment by alystair** [comment] 2018-05-15 05:59
I think this came back - every time a new update is pushed out SoundSwitch crashes, however restarts and updates correctly (however the 100% green progress bar seems to flash unusually). Running Windows 7, I've attached the log.
[tmp.txt](https://github.com/Belphemur/SoundSwitch/files/2003610/tmp.txt)

**Comment by FireEmerald** [comment] 2018-05-15 16:11
@alystair This issue was never fixed, so it can't "came back". The issue is only present if you have the classic windows skin active - do you?

**Comment by alystair** [comment] 2018-05-15 16:19
I'm using Windows 7 so... aero?                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: May 15, 2018 12:11 PMTo: SoundSwitch@noreply.github.comReply to: reply@reply.github.comCc: alystair@gmail.com; mention@noreply.github.comSubject: Re: [Belphemur/SoundSwitch] Crash on open update details when ussing Classic Windows theme (#220)  @alystair This issue was never fixed, so it can't "came back". The issue is only present if you have the classic windows skin active - do you?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by FireEmerald** [comment] 2018-05-15 16:45
Aero is **not** the Windows Classic Skin.
The **Windows Classic Skin** was included up to Windows 7. The Theme was removed in Windows 8 and Windows 10 and is no longer include.

So your issue isn't the same as described in this thread.

You can en-/disable the **Windows Classic Skin** in Windows 7 here:
![classic](https://user-images.githubusercontent.com/1107939/40070567-be31a8c0-586e-11e8-89ab-570798b25a05.png)

**Comment by alystair** [comment] 2018-05-15 17:18
Guess I'll have to open my own issue and ref this once since it's similar then                                                                                                                                                                                                            From: notifications@github.comSent: May 15, 2018 12:45 PMTo: SoundSwitch@noreply.github.comReply to: reply@reply.github.comCc: alystair@gmail.com; mention@noreply.github.comSubject: Re: [Belphemur/SoundSwitch] Crash on open update details when ussing Classic Windows theme (#220)  Aero is not the Windows Classic Skin.
The Windows Classic Skin was included up to Windows 7. The Theme was removed in Windows 8 and Windows 10 and is no longer include.
So your issue isn't the same as described in this thread.
You can en-/disable the Windows Classic Skin in Windows 7 here:


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by FireEmerald** [comment] 2020-08-26 12:09
As already mentioned, the classic theme is no longer included in recent windows versions.

Windows 7 was the last release which included the theme. As of 14th January 2020 Microsoft stopped the support for Windows 7 and therefore the OS should not be used anymore. You may use [choco](https://chocolatey.org/packages/soundswitch) to update the application without having to enter the update details window.

**Closed by FireEmerald** 2020-08-26 12:09 UTC
Labels: Bug, Confirmed
