### ISSUE TITLE
Switching output bug in Chrome

### ISSUE THREAD

**Issue by markvvaals** [Belphemur/SoundSwitch#38] opened 2015-12-05 10:57 UTC
When in Chrome, for instance watching YouTube video, switching outputs has no effect in realtime. It only has its effect after closing and re-opening Chrome. Refresh (F5) or hard refresh (CTRL+F5) both don't have an impact either.
This can also be done while another audio source is playing like WinAmp and/or VLC and they will change realtime while the Chrome audio stays on the output it was when you started the program.
Running in Admin mode changes nothing either.
All this is on version 3.6.1.12988 on Win10 clean install.

**Comment by Belphemur** [comment] 2015-12-06 18:00
Hello,

Do you have the issue with the Chrome Metro app or with the Desktop application ?
I can't reproduce it with the Desktop one.

**Comment by markvvaals** [comment] 2015-12-06 23:43
Thanks for your reply.
I'm using the regular Chrome desktop application.

I've just now tried the following:
- running SoundSwitch as admin
- re-installed SoundSwitch
- re-installed Chrome

But all to no avail. I have no idea what it can be as all other applications do switch fine just like the old version did before on Win8.1

**Comment by Belphemur** [comment] 2015-12-07 03:37
Using soundswitch you should be able to access the Playback Devices (Windows Audio Settings panel). There does the Set Defaults works ?

**Comment by markvvaals** [comment] 2015-12-07 08:35
I feel a little dumb that I didn't think of that test...
That also does not work, which makes it a Chrome issue I guess. Still a very strange one, because I cannot find others who have the same issue.

**Comment by markvvaals** [comment] 2015-12-07 23:09
Correction, the sound will SOMETIMES switch when I pause a youtube video and then switch output and will switch sometimes as well when I reload the page (either by F5 or going to home page and clicking the link again).
One more thing I noticed, when switching the outputs does not work the "system sounds" disappears in the volume mixer when you switch to any other output and comes back when you've gone full circle and are back on the output that you started on. Thus the output that (in this scenario) keeps playing the sound throughout.

**Comment by Belphemur** [comment] 2015-12-08 11:24
What soundcards do you use ?
Do you have the latest drivers for all of them ?

**Comment by Marvel2002** [comment] 2015-12-08 18:52
I confirm that i have the exact same problem with Moziilla Firefox.
It just doesn't switch directly, i need to close and re-open the browser every time except sometimes like the OP said.

Any ideas ?

Thanks

**Comment by Belphemur** [comment] 2015-12-08 21:42
@Marvel2002 same as @markvvaals. Try to switch in the windows panel first.
Also provide me
* Version of Windows (the full version): using Win+X you can run CMD as admin, in that write `winver`
* SoundCards installed and used in SoundSwitch

**Comment by markvvaals** [comment] 2015-12-08 22:29
__Windows__
  Win10 version 1511 (OS Build 10586.17)
__Onboard audio for ASUS Maximus VI Gene__
  Realtek 6.0.1.7525 (from ASUS support website)
__ASUS Xonar DGX__
  UNi Xonar 1.80 (from http://maxedtech.com/asus-xonar-unified-drivers/ ) as there are no official drivers for Win10

Note: the onboard audio has nothing plugged in, the PCIE card has speakers and mic and there is a TV hooked up to graphics card through HDMI

**Comment by Belphemur** [comment] 2015-12-09 20:31
I don't think it's going to change anything, but well you can find here the latest drivers for the Realtek: http://ivanrf.com/en/latest-asus-drivers-for-windows-10/

I use it on my laptop (G750JZ).

Your version of windows 10 is Pro or Home ?
I don't think windows made any change in the API to check for audio change ...

When you switch the audio, does SoundSwitch show a notification for it ?

**Comment by markvvaals** [comment] 2015-12-09 21:11
I'm on Win10 Pro
I get the notification every time, the output switches in "playback devices" accordingly.

Very strange behavior...

**Comment by Belphemur** [comment] 2015-12-10 02:23
I'm getting a lot of report about strange behavior in the pro version of Windows 10.

This is really weird, because the notification use the Windows API to detect change in audio device (like the change of default device). In other words, most of the application are also implementing this api to always output to the right sound card.

I begin to think it's an issue with Windows 10 Pro, since I can't reproduce it on the Home version that I own.

**Comment by markvvaals** [comment] 2015-12-10 17:25
I've just tried Firefox and the output switching works fine on that...

**Comment by kvadruppelmas** [comment] 2015-12-11 16:15
This is def a chrome issue, nothing to do with soundswitch. Prior to start using soundswitch I had the same issue when switching audio devices using the standard way to switch devices (Playback devuces, set default etc.).

Try updating Chrome to latest beta (48.0.2564.41 beta-m (64-bit)) works perfect for me now.

Im using Win 10 Pro 64-bit and have an onboard realtek chip.

To Belphemur, thank you for an excellent application makes my life alot easier :)

**Comment by Belphemur** [comment] 2015-12-12 00:28
Thanks you all for the informations about this problem.

With this last report, I'm going to close this issue since it seems to 
be caused by the browser or OS and not SoundSwitch.

**Closed** 2015-12-12 01:31 UTC
Labels: Need Informations

**Comment by markvvaals** [comment] 2015-12-12 15:34
Thanks for helping and creating such an amazing little tool which I use daily!
I can confirm that it does work correctly in the latest Chrome Beta build.
